[package]
name = "ruruby"
version = "0.1.0"
authors = ["monochrome <sisshiki@mac.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
perf = []
trace = []
emit-iseq = []
gc-debug = []
verbose = []

[dependencies]
rustyline = "5.0.3"
clap = "2.33.0"
ansi_term = "0.12.1"
regex = "1.3.7"
fancy-regex = ""
rand = "0.7.3"
divrem = ""
lazy_static = "1.4.0"