name: Rust

on:
  push:
    branches:
      - master
      - new_class

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-11-16
          override: true
      - name: Run tests
        run: cargo +nightly tarpaulin -v --out Xml --all-features --workspace
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
